# Generated by Django 6.0.4 on 2026-04-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Анонім', max_length=100, verbose_name='Автор'),
        ),
    ]
